<?php
?>


<div id="parentContainer">
    <img class='center' id="phone-image" src="images/phone.png" alt="Image description">
</div>
<h1 class="center orange">We&rsquo;re Upgrading !!!</h1>
<div id="parentContainer">
<div class="animation ">
    <div class="one spin-one"></div>
    <div class="two spin-two"></div>
    <div class="three spin-one"></div>
</div>
</div>
<p class="center">
    Oops! Our website is taking a quick break to improve your shopping experience.
    Please try again in a few minutes
</p>

<br>

<br/>
<h2 class="center quote">We&rsquo;ll be back shortly!</h2>
<h2 class="center quote">Thanks for your patience</h2>

<p class="center sign orange">&mdash; Mage249 Luma Demo</p>
